#!/bin/bash
#
# "$Id$"
#
#   IRC-backend for CUPS.
#
#   The MIT License (MIT)
#
#   Copyright (c) 2015 Adrian Pistol
#
#   Permission is hereby granted, free of charge, to any person obtaining a copy
#   of this software and associated documentation files (the "Software"), to deal
#   in the Software without restriction, including without limitation the rights
#   to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#   copies of the Software, and to permit persons to whom the Software is
#   furnished to do so, subject to the following conditions:
#
#   The above copyright notice and this permission notice shall be included in all
#   copies or substantial portions of the Software.
#
#   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#   SOFTWARE.

# Test if CUPS is querying us.
if test $# = 0; then
	echo 'network irc "IRC" "IRC Backend"'
	exit 0
fi

# Small vars
# The Backend arguments.
# printer job user title copies options [filename]
#
#     * printer - The name of the printer queue (normally this is the
#                 name of the program being run)
#     * job - The numeric job ID for the job being printed
#     * user - The string from the originating-user-name attribute
#     * title - The string from the job-name attribute
#     * copies - The numeric value from the number-copies attribute
#     * options - String representations of the job template attributes,
#             separated by spaces. Boolean attributes are provided as "name"
#             for true values and "noname" for false values.
#             All other attributes are provided as "name=value" for
#             single-valued attributes and "name=value1,value2,...,valueN"
#             for set attributes
#     * filename - The request file
# This includes $0
PRINTER="$0"
JOB="$1"
USER="$2"
TITLE="$3"
COPIES="$4"
OPTIONS="$5"
if [ "$6" == "" ] ; then
	# Read from stdin
	DATA=$(cat)
else
	DATA=$(cat $6)
fi
PDF="$TMPDIR/ircprinter.$$.print.pdf"
II_PATH="$TMPDIR/ircprinter.$$"

LOGFILE="$TMPDIR/ircprinter.log"
if [ "$DO_LOG" != "" ]; then
	touch $LOGFILE
else
	LOGFILE="/dev/null"
fi

log() { # Logs stuff
	if [ "$DO_LOG" != "" ]; then
		echo "$@"
		echo "$$: $@" >> $LOGFILE
	fi
}

send() { # Sends to II
	echo "$@" > $IRC_IN
}

cleanup() {
	# Cleanup func, removes temp files and makes sure ii is dead.
	log "Cleanup"
	rm -rf "$II_PATH" "$PDF"
	exit $1
}

trap cleanup INT TERM

# Parse DEVICE_URI
# extract the protocol, most likely "irc://"
log "parsing"
log "URI: $DEVICE_URI"
proto="$(echo $DEVICE_URI | grep :// | sed -e's,^\(.*://\).*,\1,g')"
log "Proto: $proto"
# remove the protocol
url="$(echo ${DEVICE_URI/$proto/})"
log "URL: $url"
# extract the user (if any)
name="$(echo $url | grep @ | cut -d@ -f1)"
nick=${name%%:*}
pass=${name##*:}
log "NICK: $nick"
log "PASS: $pass"
# extract the address and port
server="$(echo ${url/$name@/} | cut -d/ -f1)"
addr=${server%%:*}
port=${server##*:}
port=${port:-$PORT}
log "Server: $server"
log "addr: $addr"
log "port: $port"
# extract the chan (if any)
chan="$(echo $url | grep / | cut -d/ -f2-)"
log "Chan: $chan"

# Source config containing PUUSH API key.
LINK="λlinkλplaceλholderλyayλ"
IRC_OUT_FORMAT="$LINK"
log "sourcing config"
source /etc/default/ircprinter || exit 1

# Connect to IRC and send the PDF.
log "connecting"
ii -i "$II_PATH" -s "$addr" -p "$port" -n "$nick" -f "$REAL" &>> $LOGFILE &
IRC_SERVER_BASE="$II_PATH/$addr"
IRC_IN="$IRC_SERVER_BASE/in"

# Wait for II to init
while [ ! -e "$IRC_IN" ]; do
	sleep 1
done
if [ "$pass" != "" ]; then
	send "/PASS $pass"
fi
log "connected"
sleep 5

# Convert the PDF to use the time ii takes to initialize
log "converting"
echo -n "$DATA" | gs -dSAFER -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -sOutputFile="$PDF" -sstdout=/dev/null - || cleanup 1
log "uploading"
uploaded_pdf=`curl -s "https://puush.me/api/up" -# -F "k=$PUUSH_API_KEY" -F "z=printer" -F "f=@$PDF" | sed -E 's/^.+,(.+),.+,.+$/\1\n/'`

log "writing"
send "/JOIN $chan"
sleep 0.5
send "/PRIVMSG $chan ${IRC_OUT_FORMAT/$LINK/$uploaded_pdf}"
sleep 0.5
send "/QUIT"

# Wait
sleep 1
cleanup 0

#
# End of "$Id$".
#
