#!/bin/sh
#
# "$Id$"
#
#   IRC-backend for CUPS.
#
#   The MIT License (MIT)
#   
#   Copyright (c) 2015 Adrian Pistol
#   
#   Permission is hereby granted, free of charge, to any person obtaining a copy
#   of this software and associated documentation files (the "Software"), to deal
#   in the Software without restriction, including without limitation the rights
#   to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#   copies of the Software, and to permit persons to whom the Software is
#   furnished to do so, subject to the following conditions:
#   
#   The above copyright notice and this permission notice shall be included in all
#   copies or substantial portions of the Software.
#   
#   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#   SOFTWARE.

# Test if CUPS is querying us.
if test $# = 0; then
	echo 'direct irc "IRC" "IRC Backend"'
	exit 0
fi

# Small vars
INPUT="$6"
if [ "$6" == "" ] ; then
	# Read from stdin
	DATA=$(cat)
else
	DATA=$(cat $INPUT)
fi
PDF="/tmp/ircprinter.$$.print.pdf"
II_PATH="/tmp/ircprinter.$$"

cleanup() {
	# Cleanup func, removes temp files and makes sure ii is dead.
	rm -rf "$II_PATH"
	exit $1
}

trap cleanup INT TERM 

# Source config.
source /etc/default/ircprinter || exit 1

# Connect to IRC and send the PDF.
ii -i "$II_PATH" -s "$SERVER" -p "$PORT" -n "$NICK" -f "$REAL" &>> /tmp/out &
IRC_SERVER_BASE="$II_PATH/$SERVER"
IRC_IN="$IRC_SERVER_BASE/in"

# Wait for II to init
while [ ! -e "$IRC_IN" ]; do
	sleep 1
done
sleep 5

# Convert the PDF to use the time ii takes to initialize
echo -n "$DATA" | gs -dSAFER -sDEVICE=pdfwrite -sOutputFile="$PDF" - > /dev/null || cleanup 1
uploaded_pdf=`curl -s "https://puush.me/api/up" -# -F "k=$PUUSH_API_KEY" -F "z=printer" -F "f=@$PDF" | sed -E 's/^.+,(.+),.+,.+$/\1\n/'`

echo "/JOIN $CHAN" > $IRC_IN
echo "/PRIVMSG $CHAN $uploaded_pdf" > $IRC_IN
echo "/QUIT" > $IRC_IN

# Wait
sleep 1
cleanup 0

#
# End of "$Id$".
#
